### ISSUE TITLE
Camelot 2.0

### ISSUE THREAD

**Issue by taftse** [taftse/camelot-auth#21]
This is a general overview of all the features that CamelotAuth 2.0 will contain
We'll use this as an overview to check for things missing and to check off features which are completed.

Initial development is done by the core development team to ensure that the original vision for CamelotAuth is maintained and establishes a standard for other contributors to follow.

would you like to contribute to Camelots development and help complete this list then please comment on the individual task and/or send a pull request
## General
- [ ] Events support
### Local Form Authentication
- [x] Authenticate
- [ ] Register
- [ ] Logout
- [ ] Forgot Password
### OAuth 1 Client
- [ ] Authenticate
#### Providers
- [ ] Twitter
### OAuth 2 Client
- [ ] Authenticate
#### Providers
- [ ] Facebook
- [ ] Tumblr #12 
- [ ] Dropbox #13 
- [ ] GitHub
- [ ] Foursquare
- [ ] Google
- [ ] LinkedIn
- [ ] Microsoft (Live)
- [ ] SoundCloud
- [ ] Yammer
### OAuth 2 Server
- [x] Authenticate
- [ ] Register Apps
- [ ] Revoke Authorization
### SAML2 IDP
- [ ] Authenticate
- [ ] Add Message Signature verification #23 
### SAML2 SP
- [ ] Authenticate
- [ ] Complete samlp:Extensions #18
- [ ] Add Support for AuthnContextClassRef in AuthnRequest #22
- [ ] Add Message Signature verification #23 
### LDAP (active Directory)
- [ ] Authenticate
### OpenID
- [ ] Authenticate
## Framework Support
- [x] Laravel 4 
- [ ] CodeIgniter
- [ ] Native PHP

**Comment by nasaorc** [comment]
Can't wait for 2.0 release, OAuth 2 server functionalities just required for my project, great job bro:D
